Lista, creación y edición de sucursales
udistrital/tesoreria_cliente pull request #133
Opened 2021-10-29 21:59 UTC by diagutierrezro

udistrital/financiera_documentacion/issues/363

2021-10-30 02:59 UTC, AlexFBP requested changes

2021-11-02 16:53 UTC, AlexFBP approved these changes
Aprobado con un comentario menor...

2021-11-02 16:53 UTC, AlexFBP commented on src/app/pages/giros/sucursales/components/create-sucursal/create-sucursal.component.ts
> +        Dato: JSON.stringify({nombreSucursal: this.crearSucursalGroup.value.nombreSucursal.toUpperCase()}),
Es necesario el `toUppercase()`?
Porque si es solo a nivel de apariencia/mockup, debería realizarse con CSS y no directamente sobre el contenido
HTML:
```html
<span class="mayus">holi</span>
```
CSS: (sass/scss/less/...)
```css
.mayus {
  text-transform: uppercase;
}
```

2021-11-02 16:56 UTC, diagutierrezro commented on src/app/pages/giros/sucursales/components/create-sucursal/create-sucursal.component.ts
> +        Dato: JSON.stringify({nombreSucursal: this.crearSucursalGroup.value.nombreSucursal.toUpperCase()}),
Lo puse por mantener un estándar al momento de ingresar los datos a la db, en ocasiones puede que pongan el nombre solo en minuscula, mayuscula-minuscula, etc

2021-11-03 05:31 UTC, merged