Vista de cuentas bancarias: Tabla, crear y editar
udistrital/tesoreria_cliente pull request #141
Opened 2021-11-23 22:09 UTC by diagutierrezro

#25 
La edición de cuentas bancarias se realiza de manera correcta una vez se realicen los cambios pertinentes en giros_crud

2021-11-28 01:21 UTC, AlexFBP requested changes
Para los textos, traerlos de assets/i18n/es.json con el translate (no es necesario traducirlos a inglés, solo basta con traerlos). Esto permite, por un lado, reutilizar textos, y por otro, permite que una aplicación se pueda traducir. Ver lo comentado en las L195-199 de `src/app/pages/giros/cuentas-bancarias/components/create-cuenta/create-cuenta.component.ts` para información adicional

2021-11-28 01:21 UTC, AlexFBP commented on src/tslint.json
> +    "no-shadowed-variable": false,
Dejar en true y resolver la(s) variable(s) "shadowed" que hayan aparecido ...

```suggestion
    "no-shadowed-variable": true,
```

Se dice que una variable quedó "shadowed", "oculta" cuando queda cubierta por otra, ejemplo/típicamente, cuando una variable local tiene el mismo nombre que una variable global. Esto dificulta la detección y corrección de errores, razón por la que el linter lo advierte y bloquea

Entre [otras explicaciones y formas de resolverlo](https://stackoverflow.com/a/54105345/3180052), la típica es simplemente cambiarle el nombre a la variable que el linter está indicando como _shadowed_, bien sea a la de ámbito local (recomendado) o, a la de ámbito global

2021-11-28 01:21 UTC, AlexFBP commented on src/environments/environment.ts
> +    GIROS_CRUD_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/giros_crud/v1/',
- Agregar también al `environment.prod.ts`
- Confirmar que con el token local y el del ambiente de pruebas se pueda acceder a esta API, en caso que no, solicitar registro WSO2

2021-11-29 04:34 UTC, diagutierrezro commented on src/app/pages/giros/cuentas-bancarias/actions/cuentaBancaria.action.ts
> +    '[Giros] Crear y guardar una nueva cuenta bancaria',
Para las actions del store no es necesario usar i18n

2021-11-29 05:03 UTC, diagutierrezro commented on src/app/pages/giros/cuentas-bancarias/components/create-cuenta/create-cuenta.component.ts
> +        this.store.dispatch(obtenerRecursos({codigo: 3}));
En la carpeta interface se crea la constante para usar estas constantes

2021-11-29 05:09 UTC, diagutierrezro commented on src/app/pages/giros/cuentas-bancarias/components/table-cuentabancaria/table-cuentabancaria.component.html
> +        <h4 class="modal-title" id="borrarRegistroModal">Borrar Registro</h4>
El modal de borrar se quita ya que se manejará cambiar el estado (activo) de la cuenta bancaria

2021-11-29 05:50 UTC, diagutierrezro commented on src/app/shared/actions/shared.actions.ts
>    '[Shared] Cargar Sucursales al store',
No aplica

2021-11-29 18:28 UTC, AlexFBP approved these changes

2021-11-29 18:29 UTC, merged