feat: Se crea vista de bancos con creacioon y edicion de bancos
udistrital/tesoreria_cliente pull request #144
Opened 2021-12-21 03:23 UTC by diagutierrezro

#143

2021-12-21 22:20 UTC, AlexFBP requested changes
En general bien. La mayoría de comentarios son respecto a i18n y respecto a las ternas

Para las ternas, en general pero mayormente en...
- src/app/pages/giros/bancos/effects/bancos.effects.ts
- src/app/shared/effects/shared.effects.ts

... evitarlas o al menos desambiguarlas, agregando un paréntesis:
```javascript
A && B ? C : D
// podría interpretarse como
(A && B) ? C : D
// o bien
A && (B ? C : D)
```
De modo similar, si se requiere incluso anidar ternas, no hay problema pero se recomienda agregar paréntesis para facilitar la legibilidad.

E independientemente del nivel de anidación, donde se puedan evitar, mejor. No por nada en [Go no hay operador ternario](https://golang.org/doc/faq#Does_Go_have_a_ternary_form) a favor de la legibilidad

Editado/Notas: 
1. Si bien la precedencia y orden de evaluacion (izq/der) de operadores cambia poco entre lenguajes de programacion, evitar depender de esta precedencia
2. La "potencia", el "valor agregado" de las ternas es poder aprovechar el valor de retorno de la terna. Un criterio es que si no se va a usar el valor de retorno, es mejor cambiar a la forma "idiomatica", "legible", con un `if/else`

2021-12-22 00:03 UTC, diagutierrezro commented on src/app/shared/actions/shared.actions.ts
> +  props()
Considero que no es necesario ya que estos textos no se ven en la interfaz, estos se usan para darle un tipo de manejo al store de ngrx

2021-12-22 00:04 UTC, diagutierrezro commented on src/app/pages/giros/bancos/actions/bancos.actions.ts
> +    '[Bancos] Actualizar y guardar un tercero existente',
Considero que no es necesario ya que estos textos no se ven en la interfaz, estos se usan para darle un tipo de manejo al store de ngrx

2021-12-22 00:05 UTC, diagutierrezro commented on src/app/pages/giros/bancos/effects/bancos.effects.ts
> +                        Bancos: (data && data.Data ? data.Data : data)
Se usan paréntesis para quitarle la ambigüedad a las ternas

2021-12-22 00:15 UTC, diagutierrezro commented on src/app/shared/effects/shared.effects.ts
> +            {TipoTercero: (data && data.Data ? data.Data : data)})),
Se usan paréntesis para quitarle la ambigüedad a las ternas

2021-12-22 23:57 UTC, AlexFBP requested changes
Un ultimo ajuste y quedaría...

2021-12-22 23:57 UTC, AlexFBP commented on src/app/shared/effects/shared.effects.ts
> +            {TipoTercero: (data && data.Data ? data.Data : data)})),
Falta por desambiguar estas ternas...

2021-12-26 04:27 UTC, AlexFBP approved these changes

2021-12-26 04:27 UTC, AlexFBP commented
[Build: OK](https://hubci.portaloas.udistrital.edu.co/udistrital/tesoreria_cliente/271)

2021-12-26 04:27 UTC, merged