Se agregan los conceptos al cliente
udistrital/tesoreria_cliente pull request #150
Opened 2022-01-24 18:55 UTC by diagutierrezro

#145

2022-01-25 05:19 UTC, AlexFBP requested changes
En general bien, varias cositas menores por ajustar, dejadas como `suggested change`
Otras ya a revisar con más calma, sobretodo en relación a valores/datos "quemados"

2022-01-25 05:19 UTC, AlexFBP commented on src/app/pages/conceptos/effects/conceptos.effects.ts
> +        }
```suggestion
        private translate: TranslateService,
    ) {
    }
```

2022-01-25 05:19 UTC, AlexFBP commented on src/app/pages/conceptos/effects/conceptos.effects.ts
> +                    });
```suggestion
                    this.popupManager
                        .showSuccessAlert(this.translate.instant('CUENTA_BANCARIA.guardado_exitoso'))
                        .then((result) => {
                            if (result.value === true) this.router.navigateByUrl('pages/conceptos/lista');
                        });
```

2022-01-25 05:19 UTC, AlexFBP commented on src/app/shared/components/arbol-cuentas-contables-credito/arbol-cuentas-contables-credito.component.ts
> +    this.subCuentaContableCreditoSeleccionada$ = this.store.select(getNodoSeleccionadoCuentaContableCredito).subscribe((cuentaContable: any) => {
```suggestion
    this.subCuentaContableCreditoSeleccionada$ = this.store
    .select(getNodoSeleccionadoCuentaContableCredito)
    .subscribe((cuentaContable: any) => {
```

2022-01-25 05:19 UTC, AlexFBP commented on src/app/shared/components/arbol-cuentas-contables-debito/arbol-cuentas-contables-debito.component.html
> +</ng-container>
(En general) Dejar vacía la última línea de cualquier archivo de texto seguido por Git
```suggestion
</ng-container>

```

2022-01-25 05:19 UTC, AlexFBP commented on src/app/shared/interfaces/interfaces.ts
> +];
`OPCIONES_ENTIDAD_PRESUPUESTAL` y `OPCIONES_AREA_FUNCIONAL`  deberan tomarse de parametros_crud o de otro servicio, no deberían de estar quemados a no ser que se les trate únicamente como datos "quemados", _mock values_ para las pruebas unitarias descritas en los archivos .spec.ts (para que las pruebas sean eso: unitarias, que no dependan de factores externos)

Estas variables solo se usan para pruebas? Confirmar/coordinar con lo adelantado de la parte paramétrica con @brayanpasa99

2022-01-25 05:19 UTC, AlexFBP commented on src/app/shared/services/shared.service.ts
> +    // const unidadEjecutora = 1;
```suggestion
    // Set the optional branch for the API request.
```
O confirmar si se requieren estos comentarios...

2022-01-25 05:19 UTC, AlexFBP commented on src/app/shared/services/shared.service.ts
> +    // call request manager for the tree's data.
```suggestion
    // Set the optional branch for the API request.
    // call request manager for the tree's data.
```
O confirmar si se requieren estos comentarios...

2022-01-25 05:19 UTC, AlexFBP commented on src/environments/environment.ts
> +    // CUENTAS_CONTABLES_SERVICE: 'http://localhost:8086/v1/',
```suggestion
```

2022-01-26 17:17 UTC, diagutierrezro commented on src/app/shared/interfaces/interfaces.ts
> +];
Se habló respecto a este tema con @brayanpasa99 donde me comenta que si bien el estuvo trabajando en la parte paramétrica, no se adelantó mucho ya que fue enviado a trabajar en otros temas. Por el momento se dejarán quemados mientras se define que hacer con estos parámetros.

2022-01-27 00:57 UTC, AlexFBP requested changes
Un ajuste final/menor: Copiar/agregar la variable de entorno `CUENTAS_CONTABLES_SERVICE` a los otros environments (test.ts y prod.ts)

2022-01-28 04:34 UTC, AlexFBP approved these changes

2022-01-28 04:35 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/tesoreria_cliente/280)

2022-01-28 04:35 UTC, merged