Feature/ingresos
udistrital/tesoreria_cliente pull request #173
Opened 2022-07-01 01:20 UTC by brayanpasa99

Resuelve: udistrital/tesoreria_cliente#171

2022-07-02 01:26 UTC, AlexFBP requested changes
En general, bien.
Un ajuste menor respecto a una dependencia y quedaría...

2022-07-02 01:26 UTC, AlexFBP commented on src/app/pages/ingresos/components/lista-ingresos/lista-ingresos.component.ts
> +import { PopUpManager } from '../../../../@core/managers/popUpManager';
```suggestion
import { PopUpManager } from '../../../../@core/managers/popUpManager';
```
En lo posible, evitar las dependencias directas de `Swal`: El `PopUpManager` internamente abstrae el uso de `Swal`. Si es necesario mostrar avisos en cascada, hacer que el `PopUpManager` retorne el evento Swal

2022-07-02 04:20 UTC, AlexFBP approved these changes

2023-02-13 22:00 UTC, brayanpasa99 commented
Se cierra dado que ya no tengo vinculación con la organización

2023-02-13 22:00 UTC, closed without merging