Feature/avances/solicitudavances
udistrital/tesoreria_cliente pull request #22
Opened 2021-02-08 23:52 UTC by dmarcela09

- [ ] Se crea la interfaz de solicitud de avances issue #11 :

Vista de lista de solicitudes
![imagen](https://user-images.githubusercontent.com/26507343/107295547-9036ec80-6a3d-11eb-8b79-9c2736a7f374.png)
Nueva solicitud de avance - Inicio
![imagen](https://user-images.githubusercontent.com/26507343/107295583-a8a70700-6a3d-11eb-87f5-02d192d0dd38.png)
Descripción
![imagen](https://user-images.githubusercontent.com/26507343/107295636-c5433f00-6a3d-11eb-9141-280e3ee5a60c.png)
Tipo de Avance
![imagen](https://user-images.githubusercontent.com/26507343/107295724-f7ed3780-6a3d-11eb-90e3-986b728350ac.png)
Detalle de tipos de avances agregados
![imagen](https://user-images.githubusercontent.com/26507343/107295774-13f0d900-6a3e-11eb-9e8e-618f66cda26c.png)
Resumen de solicitud
![imagen](https://user-images.githubusercontent.com/26507343/107295817-2a973000-6a3e-11eb-8ca0-186d84e78664.png)

- [ ] Tambien se hacen ajustes en la vista Tipos de Avance para el enlace de la norma agregando la posibilidad de actualizar y ver un historial de las normas anteriores:

![imagen](https://user-images.githubusercontent.com/26507343/107295876-51edfd00-6a3e-11eb-9589-fc82c0dcda05.png)
![imagen](https://user-images.githubusercontent.com/26507343/107295915-6205dc80-6a3e-11eb-9bcc-2822e2ac3ccd.png)

2021-02-09 04:21 UTC, BOTOOM requested changes

2021-02-09 04:21 UTC, BOTOOM commented on src/app/pages/avances/solicitudavances/components/set-descripcion/set-descripcion.component.html
> +                <input type="text" class="form-control" formControlName="convenio" [class.is-invalid]="convenioInvalid">
el nombre de convenio se trae con el convenio asi que debería de estar el campo text desactivado

2021-02-09 04:21 UTC, BOTOOM commented on src/app/pages/avances/solicitudavances/components/set-descripcion/set-descripcion.component.html
> +                <input type="text" class="form-control" formControlName="investigacion" [class.is-invalid]="investigacionInvalid">
lo mismo para este campo

2021-02-09 04:21 UTC, BOTOOM commented on src/app/pages/avances/solicitudavances/components/show-detalleavance/show-detalleavance.component.html
> +                    <div class="collapse" id="collapseTiposAvances">
en el resumen el boton de agregar no debería aparecer
![imagen](https://user-images.githubusercontent.com/28914781/107314849-8fb14c80-6a63-11eb-9e36-17b200beb057.png)

2021-02-09 18:27 UTC, dmarcela09 commented on src/app/pages/avances/solicitudavances/components/show-detalleavance/show-detalleavance.component.html
> +                    <div class="collapse" id="collapseTiposAvances">
He realizado los cambios necesarios en el commit nuevo.

2021-02-10 01:41 UTC, BOTOOM approved these changes

2021-02-10 01:41 UTC, merged